### ISSUE TITLE
hi, I,meet problem when run train.py.  Read PCD failed: unable to open file: ./datasets/tless/models/1.pcd

### ISSUE THREAD

**Issue by yuheyuan** [GANWANSHUI/ES6D#4]
When I run 
```python
$ python train.py --loss_type GADD
```
it will occours

```python
[Open3D WARNING] Read PCD failed: unable to open file: ./datasets/tless/models/1.pcd
```

I only down load the t-less datasets, and follow your step
But I find there exactly no exit pcd files. It only exits ply files.
So how can I solve it.

here is my run results
```txt
init gps:0
init gps:1
[Open3D WARNING] Read PCD failed: unable to open file: ./datasets/tless/models/1.pcd
utput:  1 0 3
[Open3D WARNING] Read PCD failed: unable to open file: ./datasets/tless/models/1.pcd
utput:  1 0 3
Traceback (most recent call last):
  File "train.py", line 474, in <module>
    main()
  File "train.py", line 115, in main
    mp.spawn(per_processor, nprocs=opt.gpu_number, args=(opt,))
  File "/home/ailab/anaconda3/envs/yy_ES6D/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 199, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/ailab/anaconda3/envs/yy_ES6D/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 157, in start_processes
    while not context.join():
  File "/home/ailab/anaconda3/envs/yy_ES6D/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 118, in join
    raise Exception(msg)
Exception: 

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/home/ailab/anaconda3/envs/yy_ES6D/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/media/ailab/data/yy/ES6D-master/train.py", line 231, in per_processor
    dataset = pose_dataset('train', opt.num_points, opt.dataset_root, True, opt.noise_trans)
  File "/media/ailab/data/yy/ES6D-master/datasets/tless/tless_dataset.py", line 62, in __init__
    xyz_ids = farthest_point_sample(raw_xyz, num_pt).cpu().numpy()
  File "/media/ailab/data/yy/ES6D-master/datasets/tless/tless_dataset.py", line 223, in farthest_point_sample
    farthest = torch.randint(0, N, (B,), dtype=torch.long).to(device)
RuntimeError: random_ expects 'from' to be less than 'to', but got from=0 >= to=0

```

**Comment by yuheyuan** [comment]
Did I miss download something ? I truly download t-less models.

**Comment by GANWANSHUI** [comment]
Hi, we downsample the ply files into PCB to reduce the computational cost. I have uploaded the PCB model to: https://www.dropbox.com/sh/zxq5lx71zpq4nts/AAALVgeSvszpHEy8CUBr8iala?dl=0. Thanks a lot for the reminder!

**Comment by yuheyuan** [comment]
> Hi, we downsample the ply files into PCB to reduce the computational cost. I have uploaded the PCB model to: https://www.dropbox.com/sh/zxq5lx71zpq4nts/AAALVgeSvszpHEy8CUBr8iala?dl=0. Thanks a lot for the reminder!

oh, I success . Thank you
